name: Build Docker Images

# Add permissions configuration
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch:
    inputs:
      validator_branch:
        description: 'Validator branch to use'
        required: true
        default: 'itn4-1.16.3'
        type: string
      cli_branch:
        description: 'CLI branch to use'
        required: true
        default: 'itn4'
        type: string
      gui_branch:
        description: 'GUI branch to use'
        required: true
        default: 'itn4'
        type: string
      tag:
        description: 'Tag for the Docker images'
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: [self-hosted, Linux, X64]
          - arch: arm64
            runner: [self-hosted, Linux, ARM64]
    runs-on: ${{ matrix.runner }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --no-cache \
            --platform linux/${{ matrix.arch }} \
            --build-arg VALIDATOR_BRANCH=${{ inputs.validator_branch }} \
            --build-arg CLI_BRANCH=${{ inputs.cli_branch }} \
            --build-arg GUI_BRANCH=${{ inputs.gui_branch }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ inputs.tag }} \
            .

      - name: Push Docker image and cleanup
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ inputs.tag }}
          # Remove the image after pushing
          docker rmi ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ inputs.tag }}
          
  create-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create and push manifest
        run: |
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-amd64:${{ inputs.tag }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-arm64:${{ inputs.tag }}
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }} 
