name: Build Docker Images

# Add permissions configuration
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network to build for'
        required: true
        type: choice
        options:
          - mainnet
          - stagenet
          - testnet
        default: 'testnet'
      validator_branch:
        description: 'Validator branch to use'
        required: true
        default: 'mainnet-launch'
        type: string
      cli_branch:
        description: 'CLI branch to use'
        required: true
        default: 'mainnet-launch'
        type: string
      gui_branch:
        description: 'GUI branch to use'
        required: true
        default: 'mainnet-launch'
        type: string
      tag:
        description: 'Tag for the Docker images'
        required: true
        type: string

jobs:
  build:
    if: ${{ inputs.tag != 'latest' }}
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: [self-hosted, Linux, X64]
          - arch: arm64
            runner: [self-hosted, Linux, ARM64]
    runs-on: ${{ matrix.runner }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image using script
        run: |
          ./scripts/build-network.sh ${{ inputs.network }} ${{ inputs.tag }} ${{ matrix.arch }} ${{ env.REGISTRY }}

      - name: Push Docker image and cleanup
        run: |
          # Construct the image name exactly as the script does
          IMAGE_NAME_FULL="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ inputs.network }}-${{ inputs.tag }}"
          echo "Pushing: $IMAGE_NAME_FULL"
          docker push "$IMAGE_NAME_FULL"
          # Remove the image after pushing
          echo "Removing: $IMAGE_NAME_FULL"
          docker rmi "$IMAGE_NAME_FULL"
          
  create-manifest:
    needs: build
    if: ${{ inputs.tag != 'latest' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create and push manifest per network
        run: |
          MANIFEST_NAME="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.network }}-${{ inputs.tag }}"
          IMG_AMD64="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-amd64:${{ inputs.network }}-${{ inputs.tag }}"
          IMG_ARM64="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-arm64:${{ inputs.network }}-${{ inputs.tag }}"
          echo "Creating manifest: $MANIFEST_NAME from $IMG_AMD64 and $IMG_ARM64"
          docker manifest create "$MANIFEST_NAME" \
            "$IMG_AMD64" \
            "$IMG_ARM64"
          echo "Pushing manifest: $MANIFEST_NAME"
          docker manifest push "$MANIFEST_NAME" 
